---
title: Stream Analyze
timezone: Europe/Stockholm
collections:
  features:
    title: Features
    output: false
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  strengths:
    title: Strengths
    output: false
  uploads:
    title: Uploads
    output: true
email: hello@streamanalyze.com
description: Stream Analyze specialize in software for scalable on-line analyses of
  streamed data.
url: https://streamanalyze.github.com
twitter_username: streamanalyze
github_username: streamanalyze
markdown: kramdown
exclude:
- README.md
- Gemfile
- Gemfile.lock
- sass
- scss
- .gitignore

sass:
  sass_dir: _scss
  style: compressed
